name: terraform

env:
  # e.g. projects/123456789/locations/global/workloadIdentityPools/github-actions/providers/github-actions
  WORKLOAD_IDENTITY_PROVIDER: "" # TODO: Edit here

  # e.g. terraform@GCP_PROJECT_ID.iam.gserviceaccount.com
  SERVICE_ACCOUNT_EMAIL: "" # TODO: Edit here

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    concurrency: terraform-tfstate
    environment: ${{ ((github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && 'terraform-apply') || '' }}

    steps:
      - uses: actions/checkout@v5
        with:
          # Make `fetch-depth` larger because the default value(1) causes `git merge-base --is-ancestor origin/main` to fail.
          fetch-depth: 100

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Set variables
        run: |
          TERRAFORM_VERSION=$(cat .terraform-version)
          echo "TERRAFORM_VERSION=$TERRAFORM_VERSION" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          # c.f. https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform init -input=false

      - name: terraform fmt
        run: |
          set +e
          terraform fmt -recursive -check
          ret=$?
          set -e

          if [ $ret -ne 0 ]; then
            echo '[ERROR] Run `terraform fmt -recursive` or fix followings'
            terraform fmt -recursive
            git --no-pager diff
          fi
          exit $ret

      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: terraform plan
        id: plan
        run: terraform plan -input=false -no-color

      - name: Post terraform plan report to PullRequest comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ci_url = "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: [\`${{ github.workflow }}\`](${ ci_url })*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Post terraform plan report to Job Summaries
        uses: actions/github-script@v7
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ci_url = "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: [\`${{ github.workflow }}\`](${ ci_url })*`;

            await core.summary
              .addHeading('Terraform plan report')
              .addRaw("\n" + output)
              .write()

      - name: Prevent apply on old commits
        run: |
          default_branch=`git remote show origin | grep 'HEAD branch:' | cut -d : -f 2 | tr -d '[[:space:]]'`
          git fetch
          if [ -n "$PR_HEAD_SHA" ]; then
            export GITHUB_SHA=$PR_HEAD_SHA
          fi
          echo '[ERROR] Run `git rebase` if following fails'
          git merge-base --is-ancestor origin/${default_branch} ${GITHUB_SHA}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

      - name: terraform apply (main push, manual running)
        run: |
          terraform apply -input=false -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

      - name: Slack Notification
        uses: act10ns/slack@v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
